apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: prometheus
    prometheus: prometheus-prometheus
  name: prometheus-prometheus-db
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 15Gi
  storageClassName: prometheus
  volumeMode: Filesystem
  volumeName: prometheus-pv-logs

